version: '2'
services:
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app/test_qos
      - bundle:/bundle
    environment:
      RAILS_ENV: development

volumes:
  bundle:
    driver: local
